version: "3"

services:
  source_db:
    image: postgres:13.4-alpine
    restart: always
    container_name: db_migration_source_db
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5443:5432"
    volumes:
      - ./source_db_data:/var/lib/postgresql/data/

  destination_db:
    image: postgres:13.4-alpine
    restart: always
    container_name: db_migration_destination_db
    env_file:
      - ./.env
    expose:
      - 5432
    ports:
      - "5444:5432"
    volumes:
      - ./dest_db_data:/var/lib/postgresql/data/

  script:
    build: ./
    restart: always
    container_name: db_migration_script
    command: sh -c "python -m main.py"
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    depends_on:
      - source_db
      - destination_db
