version: "3"

services:
  source_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: db_migration_source_db
    env_file:
      - ./.env
    expose:
      - 1433
    ports:
      - "1433:1433"
    volumes:
      - ./source_db_data:/var/opt/mssql

  destination_db:
    image: mysql/mysql-server:8.0
    restart: always
    container_name: db_migration_destination_db
    env_file:
      - ./.env
    expose:
      - 3308
    ports:
      - "3308:3306"
    volumes:
      - ./dest_db_data:/var/lib/mysql

  script:
    build: ./
    restart: always
    container_name: db_migration_script
    command: sh -c "python -m main.py"
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./:/app:cached
    depends_on:
      - source_db
      - destination_db
